apiVersion: v1
data:
    credentials-linkding.json: ENC[AES256_GCM,data:edk11PLkLgX4oPudb2uQkrlnWqAWAFZVocFELoulc4IxqJ++HzTIECC29T6RjnYkFO2HIZBzbszSh5cdEVsfS4um4RuSahaEg/C7PHXLUrNoTTZLnUKJmtv6zxDn1liSxswLmXbZjK2CmiTidrUY777rg5mflbBuxpTrPgim57+WLGdKJzcXSl3l3k3Aof8DlNNdk8vREAIsn2R5T0GqWu+80F/mA6H4UpgtPBjPvydnw70WXchjR2IY5NyVNumNTJiYQfK17qEgc+RIhTH0AKrxPVxt6Z484ub1p0Eil5A716D8S1hcFRSrshs=,iv:4e6dl559a/3wHjtL5x1ErJKG46uBqcsUDVRLNh/IUmU=,tag:PgDHTFfbiJqVkfWrrP6gMQ==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials-linkding
sops:
    age:
        - recipient: age10k28kkfyvws4ukkk4qy5aw5talf24cyh9xluhxdmeysflgza3gsqvazsek
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUV0pVZndRQTgxZkJ5Qkx6
            ek9QcHFrVW9JTlNIeEdMWVM5Sjl5cTZGeVhNClU2SEE0NHVYalV3MG5GK3FhZGZW
            cnlNRzFpZWRKSHpIbU40WTIvRk4rdncKLS0tIHpnWFBEcEVzdVJHbXJYZzFabEtL
            Mmt2OE9wMHplR1Rtcko3Sm5rNTBXc0kKJHrU3FXUkUmSWMPuC4ftNcI7MZP39mw8
            FBCH6Ah35v7+krjjxnCbJrRol3K+KA9brgDyE+jD2fpqA5lqid3Kow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T21:20:58Z"
    mac: ENC[AES256_GCM,data:6wt2iKHy4lJunvMTu/5VnSN1zVLAOPS0Tl+RthV46GTvAGk8L+UrGbKANu6BzMTNOsD39OtjX+JvAJO/DCZFmolVk1NVSij97eQJXu19OcUoHAmeuQyZmWgx6YRV+8fzyYaAVgly/ZZvioeuWq4I5gXPP+FRBB/Hf7vM70+jhc4=,iv:JaP9u9DJHTJt1CHtGFQO64zNyq6Rtb9DIA2iYIspCBc=,tag:wJxYTOI9wVHB3RthMJ+PtQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
