apiVersion: v1
data:
    72376d50-0d2e-4d2b-91b2-f6c933c81c7d.json: ENC[AES256_GCM,data:k7I+6ED/DHrWnkAs2HOse2qbwKKQQ2hIDXiO4z2KYTRXmAXdrzCqXvvOGNUUEQOeF6eYXZrTUjTtm/xzDdbGogk1Ehcp0H/TiE6cMtCVk/m9/ZZBfxjwgEC0fAtx4O4BU6WhOaCvstihF6Mly4YtHZeijeLjqrctq6xNlv8RIK8Y2lZBMDEPdedzj+Y8AZ5J83XZyXjL6nOzNti6L018jovpI295cBD7fDi+5O1eCcEk4JIw327zfOjOzhOJ0jGgDZV0v1tu/cJEKLUeU6bxzYhcE89vdqIq2KYuOJhlVmGbeJU04PxZXd78TtM=,iv:jW8y6ucKBUv9AOUZkecjIx72++c/PpP+e36GVqEU/+s=,tag:5KWmD7H0MSvgBSD77qS/EA==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials-mealie
sops:
    age:
        - recipient: age10k28kkfyvws4ukkk4qy5aw5talf24cyh9xluhxdmeysflgza3gsqvazsek
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFSzEzZUV0emRVeXV2SXI1
            S2hiNFY2L0xLd1lEWHJueUF0TEpuUlBoQ1NnCktQWStqU0luaS9TL1R3K2FZYlJD
            a1ZzL0dRc2hWcFNpMGJiRExzYXcxTEUKLS0tIEE3M3hqTTdaYVdjWGc2QlN1Y00z
            TE05NlpOUmMvZTEyYWZMN2xkVDM4MzgKIMDslrG42ov1CD3bNLWID3udOv5lfAYK
            accsnaJ4FRWPRaCB7Ur3MrlbbtewPPVHDfQJHVrUWv+xB4tyJHMTig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T19:27:35Z"
    mac: ENC[AES256_GCM,data:C0FCw8/THyfhKBD6z9eeshgzGH93Gi/vPBlIIRV1mVYg0+vE2JQi6vkJPh+huiVmAjYYtkl3CBm33LbmmaGWamF413GJ9ELwGmHHOqpXo2nopjTOQhOxLC3+kspvLJApt9+HthApU7QdCc3JNpnqZ1A9UVn1r+BnJuAUoI1shCA=,iv:WoQs9sdrg7Jab54dCtyk5preyi4vrE2+glthRZbgoag=,tag:T6hyhnpFZ/gh8LJUd6bMUg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
