apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: renovate-controllers
  namespace: flux-system
spec:
  interval: 1m0s
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/controllers/cat-k3s
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
#---
#apiVersion: kustomize.toolkit.fluxcd.io/v1
#kind: Kustomization
#metadata:
#  name: renovate-configs
#  namespace: flux-system
#spec:
#  interval: 1m0s
#  retryInterval: 1m
#  timeout: 5m
#  sourceRef:
#    kind: GitRepository
#    name: flux-system
#  path: ./infrastructure/configs/cat-k3s
#  prune: true
#  decryption:
#    provider: sops
#    secretRef:
#      name: sops-age
