apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-client-retain
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: nfs-subdir-external-provisioner
reclaimPolicy: Retain

