apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linkding-data-pvc
  namespace: linkding
spec:
  volumeName: linkding-data-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
