apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linkding-data-pvc
  namespace: linkding
spec:
  storageClassName: nfs-retain-linkding
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
