apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "80.6.0"
      sourceRef:
        kind: HelmRepository
        name: kube-prometheus-stack
        namespace: flux-system
      interval: 10m
  values:
    replicaCount: 2
